services:
  trade-mysql:
    image: mysql:latest
    restart: always
    env-file: "mysql.env"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql/
  #  networks:
  #    - backend
    environment:
      - MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      - MYSQL_DATABASE: "${MYSQL_DATABASE}"
      - MYSQL_USER: "${MYSQL_USER}"
      - MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
